// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuVxmBqSPMiDlm7mVH36EgRRmjkJ4Rsc0',
    appId: '1:723033217072:web:fdf16244c2d8a52824f5f5',
    messagingSenderId: '723033217072',
    projectId: 'chatapp-88cdf',
    authDomain: 'chatapp-88cdf.firebaseapp.com',
    storageBucket: 'chatapp-88cdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKsG4i3OiIg59aGYe2LugaYDcvLti4I_U',
    appId: '1:723033217072:android:573727c73233a9ef24f5f5',
    messagingSenderId: '723033217072',
    projectId: 'chatapp-88cdf',
    storageBucket: 'chatapp-88cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn5Q5BcS_3L7qYetWsxHOCJctM5P36_OA',
    appId: '1:723033217072:ios:c28fb88a915203f024f5f5',
    messagingSenderId: '723033217072',
    projectId: 'chatapp-88cdf',
    storageBucket: 'chatapp-88cdf.appspot.com',
    androidClientId: '723033217072-cjk6r29b0tvn6o8nqh8lnbv5gml9o595.apps.googleusercontent.com',
    iosClientId: '723033217072-u1e8u7l009immouk1p2orpdaqapg1mlr.apps.googleusercontent.com',
    iosBundleId: 'com.ikhwan.app',
  );
}
